# Generated by Django 6.0.7 on 2026-07-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('login', 'User Login'), ('low_stock', 'Low Stock'), ('edit', 'Edit Alert'), ('arrival', 'Items Arrived'), ('stock_in', 'Stock In'), ('stock_out', 'Stock Out'), ('info', 'Info')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Notification', max_length=100),
        ),
    ]
