# Generated by Django 6.0.7 on 2026-07-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='device',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
