# Generated by Django 6.0.7 on 2026-07-29 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('purchase_orders', '0004_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='companies.company'),
        ),
    ]
