# Generated by Django 6.0.7 on 2026-08-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
