# Generated by Django 6.0.7 on 2026-08-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_is_private'),
    ]

    operations = [
    ]
