# Generated by Django 6.0.7 on 2026-07-13 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_warehouse'),
        ('warehouses', '0002_warehouse_capacity_warehouse_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'warehouse_stocks',
                'unique_together': {('warehouse', 'product')},
            },
        ),
    ]
