# Generated by Django 6.0.7 on 2026-07-11 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_reorder_point'),
        ('warehouses', '0002_warehouse_capacity_warehouse_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='warehouses.warehouse'),
        ),
    ]
