# Generated by Django 6.0.7 on 2026-07-13 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='warehouse',
        ),
    ]
