# Generated by Django 6.0.7 on 2026-08-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_company'),
        ('products', '0007_product_company_alter_product_sku_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='categories.category'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
